# Generated by Django 4.1.4 on 2023-01-21 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petparent', '0002_petcareadvert_petadoptionadvert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petadoptionadvert',
            old_name='pet_photo',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='petcareadvert',
            name='date_from',
            field=models.DateField(default=datetime.date(2023, 1, 23), help_text='04.10.2023'),
        ),
        migrations.AlterField(
            model_name='petcareadvert',
            name='date_to',
            field=models.DateField(default=datetime.date(2023, 1, 26), help_text='08.10.2023'),
        ),
    ]
