# Generated by Django 4.1.4 on 2023-01-22 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petparent', '0003_rename_pet_photo_petadoptionadvert_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petadoptionadvert',
            name='photo',
            field=models.ImageField(blank=True, default='image_placeholder.png', upload_to='pet_photos/'),
        ),
        migrations.AlterField(
            model_name='petcareadvert',
            name='date_from',
            field=models.DateField(default=datetime.date(2023, 1, 24), help_text='04.10.2023'),
        ),
        migrations.AlterField(
            model_name='petcareadvert',
            name='date_to',
            field=models.DateField(default=datetime.date(2023, 1, 27), help_text='08.10.2023'),
        ),
    ]
