# Generated by Django 4.1.4 on 2023-01-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petparent', '0004_alter_petadoptionadvert_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petadoptionadvert',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/'),
        ),
    ]
