# Generated by Django 4.1.4 on 2023-01-23 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petparent', '0005_alter_petadoptionadvert_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petcareadvert',
            name='date_from',
            field=models.DateField(default=datetime.date(2023, 1, 25), help_text='04.10.2023'),
        ),
        migrations.AlterField(
            model_name='petcareadvert',
            name='date_to',
            field=models.DateField(default=datetime.date(2023, 1, 28), help_text='08.10.2023'),
        ),
    ]
