# Generated by Django 4.1.4 on 2023-01-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petparent', '0007_alter_petadoptionadvert_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petadoptionadvert',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/'),
        ),
    ]
